# Generated by Django 2.2 on 2019-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0002_auto_20190422_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
