# Generated by Django 2.2 on 2019-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0006_auto_20190422_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
