# Generated by Django 2.2 on 2019-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0007_customuser_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
