# Generated by Django 2.2 on 2019-05-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0011_customuser_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photos',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
