# Generated by Django 2.2 on 2019-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0016_auto_20190502_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(default=None, max_length=90),
        ),
    ]
