# Generated by Django 2.2 on 2019-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0017_auto_20190502_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=90, null=True),
        ),
    ]
