# Generated by Django 2.2 on 2019-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0019_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='doctors',
            name='available_time_end',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='doctors',
            name='available_time_start',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='doctors',
            name='mobile_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='qualification',
            field=models.TextField(default=None),
        ),
    ]
