# Generated by Django 2.2 on 2019-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0022_auto_20190508_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photos',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
