# Generated by Django 2.2 on 2019-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0024_auto_20190508_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
