# Generated by Django 2.2 on 2019-05-19 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0025_remove_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeebBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsub', models.CharField(default=None, max_length=100)),
                ('tmessage', models.TextField(default=None)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
