# Generated by Django 2.2 on 2019-05-19 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0026_feebback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feebback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
