# Generated by Django 2.2 on 2019-05-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0027_auto_20190519_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='available_time_end',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='available_time_start',
        ),
    ]
