# Generated by Django 2.2 on 2019-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0028_auto_20190521_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctorphoto',
            field=models.FileField(default=None, upload_to='doctor/'),
        ),
    ]
