# Generated by Django 2.2 on 2019-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0031_doctors_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='positions',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
