# Generated by Django 2.2 on 2019-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0032_doctors_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='positions',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
