# Generated by Django 2.2 on 2019-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0033_auto_20190522_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pass_reset',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
