# Generated by Django 2.2 on 2019-05-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0034_customuser_pass_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pass_reset',
            field=models.BooleanField(default=None),
        ),
    ]
