# Generated by Django 2.2 on 2019-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0036_medicalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='prescription',
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='add_info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='docotr_email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_10',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_6',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_7',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_8',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='drug_limit_9',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_10',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_6',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_7',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_8',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='eat_time_9',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='history',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_10',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_6',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_7',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_8',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='medi_name_9',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_10',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_6',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_7',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_8',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='num_of_day_9',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='test_advise',
            field=models.TextField(default=None),
        ),
    ]
