# Generated by Django 2.2 on 2019-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0038_auto_20190524_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='adate',
            field=models.DateField(default=None),
        ),
    ]
