# Generated by Django 2.2 on 2019-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0040_remove_medicalinfo_adate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='adate',
            field=models.DateField(default=None),
        ),
    ]
