# Generated by Django 2.2 on 2019-05-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0041_medicalinfo_adate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='adate',
        ),
    ]
