# Generated by Django 2.2 on 2019-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0043_medicalinfo_adate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
