# Generated by Django 2.2 on 2019-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0044_medicalinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
