# Generated by Django 2.2 on 2019-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0045_auto_20190527_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('Medicine_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('medicinename', models.CharField(default=None, max_length=200)),
                ('medicineRegno', models.CharField(default=None, max_length=200, unique=True)),
                ('medicinebefore', models.IntegerField(default=None)),
                ('medicineafter', models.IntegerField(default=None)),
                ('medicinenow', models.IntegerField(default=None)),
            ],
        ),
    ]
